version: '3.7'

services:
  ethancedwards:
    image: ethancedwards8/ethancedwards-quotes
    networks:
      - traefik-public
      - ethancedwards-internal
    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.ece-quotes-http.rule=Host(`${DOMAIN1?Variable not set}`)
        - traefik.http.services.ece-quotes-http.loadbalancer.server.port=80
        - traefik.http.routers.ece-quotes-http.entrypoints=http
        - traefik.http.routers.ece-quotes-http.middlewares=https-redirect
        - traefik.http.routers.ece-quotes-https.rule=Host(`${DOMAIN1?Variable not set}`)
        - traefik.http.routers.ece-quotes-https.entrypoints=https
        - traefik.http.routers.ece-quotes-https.tls=true
        - traefik.http.routers.ece-quotes-https.tls.certresolver=le
networks:
  traefik-public:
    external: true
  ethancedwards-internal:
    external: false
